cache:
  paths:
    - .cache/pip
    - venv/
  key: "$CI_JOB_IMAGE-$CI_COMMIT_REF_SLUG"

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - "lint"
  - "test"

.build:
    before_script:
        - "pip --version"
        - "pip install virtualenv"
        - "python -m virtualenv venv"
        - "source venv/bin/activate; pip install docker"
        - "source venv/bin/activate; pip show docker"
        - "apt-get update -y"
        - "apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y"
        - "curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -"
        - "add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable\""
        - "apt-get update -y"
        - "apt-get install docker-ce docker-ce-cli containerd.io -y"
        - "service docker start"
        - "while systemctl is-active docker | grep \"inactive\" --q; do sleep 1; done"
        - "service docker status"
        - "docker info"
        - "source venv/bin/activate; python setup.py sdist"
        - "source venv/bin/activate; pip install --upgrade pip"
        - "source venv/bin/activate; pip install -r requirements-dev.txt"
        - "source venv/bin/activate; pip install docker>=2.5.1"
        - "source venv/bin/activate; pip install boto==2.45.0"
        - "source venv/bin/activate; pip install boto3"
        - "source venv/bin/activate; pip install dist/moto*.gz"
        - "source venv/bin/activate; pip install coveralls==1.1"
        - "source venv/bin/activate; pip install coverage==4.5.4"

lint:
  extends: .build
  stage: lint
  image: "python:3.7"
  script:
    - make lint

test-2.7:
  stage: test
  extends: .build
  image: "python:2.7"
  script:
    - make athena-test

test-3.6:
  stage: test
  extends: .build
  image: "python:3.6-buster"
  script:
    - make athena-test

test-3.7:
  stage: test
  extends: .build
  image: "python:3.7"
  script:
    - make mbc-test