# action.yml
name: 'Release Moto'
description: 'Release Moto with the version supplied'
inputs:
  version:  # id of input
    description: 'Version number'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        pwd
        ls -la /home/runner/work/moto/moto
      shell: bash
    - run: echo ${{ inputs.version }} > VERSION
      shell: bash
    - run: echo "lets see if ${{ inputs.version}} exists.."
      shell: bash
    - run: echo "lets see if envs exist ${{ env.version }}"
      shell: bash
    - run: echo "Use file $(cat VERSION)"
      shell: bash
    - run: |
        ! git rev-parse ${{ inputs.version }}
      shell: bash
    - run: grep ${{ inputs.version }} CHANGELOG.md || echo "Ensure that the CHANGELOG contains an entry for ${{ inputs.version }}"
      shell: bash
    - run: |
        echo "TODO: update __init__.py"
      shell: bash
    - run: |
        echo "make publish"
      shell: bash
