# action.yml
name: 'Release Moto'
description: 'Release Moto with the version supplied'
inputs:
  version:  # id of input
    description: 'Version number'
    required: true
runs:
  using: 'composite'
  steps:
    - run: pip install wheel setuptools --upgrade
      shell: bash
    - run: |
        ! git rev-parse ${{ inputs.version }}
      shell: bash
    - run: grep ${{ inputs.version }} CHANGELOG.md || { echo "Ensure that the CHANGELOG contains an entry for ${{ inputs.version }}" ; exit 1; }
      shell: bash
    - run: |
        python update_version_from_git.py ${{ inputs.version }}
      shell: bash
    - run: make publish
      shell: bash
