# action.yml
name: 'Release Moto'
description: 'Release Moto with the version supplied'
inputs:
  version:  # id of input
    description: 'Version number'
    required: true
  twine_user:
    description: 'Twine Username'
    required: true
  twine_pass:
    description: 'Twine Password'
    required: true
  docker_user:
    description: 'DockerHub Username'
    required: true
  docker_token:
    description: 'DockerHub Token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: pip install wheel setuptools packaging twine --upgrade
      shell: bash
    - name: Verify supplied version is not a GitHub tag yet
      run: |
        ! git rev-parse ${{ inputs.version }} || { echo "Ensure that no tag exists for ${{ inputs.version }}" ; exit 1; }
      shell: bash
    - name: Verify supplied version exists in the CHANGELOG
      run: grep ${{ inputs.version }} CHANGELOG.md || { echo "Ensure that the CHANGELOG contains an entry for ${{ inputs.version }}" ; exit 1; }
      shell: bash
    - name: Set desired version number
      run: |
        python update_version_from_git.py ${{ inputs.version }}
      shell: bash
    - name: Build and Upload
      env:
        TWINE_USER: ${{ inputs.twine_user }}
        TWINE_PASSWORD: ${{ inputs.twine_pass }}
      run: |
        pip show twine
        python setup.py sdist bdist_wheel
        python -m twine upload --repository testpypi dist/* --non-interactive
      shell: bash
    - name: Tag version on Github
      run: |
        git tag `python setup.py --version`
        git push origin `python setup.py --version`
      shell: bash
    - name: Push Docker version
      run: |
        echo ${{ inputs.docker_token }} | docker login --username ${{ inputs.docker_user }} --password-stdin
        docker build -t bblommers/mototestreleases  . --tag moto:`python setup.py --version`
        docker push bblommers/mototestreleases
        docker logout
      shell: bash
    - name: Increase patch version number
      run: |
        python update_version_from_git.py patch
        git add moto/__init__.py
        git commit -m "Increase version number post-release"
        git push
      shell: bash
