# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'composite'
  steps:
    - run: |
        pwd
        ls -la /home/runner/work/moto/moto
      shell: bash
    - run: |
        echo "TODO: verify our version does not yet exist"
      shell: bash
    - run: |
        echo "TODO: verify changelog contains our version"
      shell: bash
    - run: |
        echo "TODO: update __init__.py"
      shell: bash
    - run: |
        echo "make publish"
      shell: bash
