on:
  push:
    branches:
      - test-automate-release
    # Only run when we're editing this file (for testing purposes)
    paths:
      - '.github/workflows/release.yml'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: bblommers/moto-release-action@latest
      with:
        who-to-greet: 'Mona the Octocat wants to release ${{ github.event.inputs.version }}'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"