name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Release Moto
      uses: ./.github/actions/moto-release/
      with:
        version: '${{ github.event.inputs.version }}'
