name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: ''

jobs:
  release-moto-job:
    runs-on: ubuntu-latest
    name: Release Moto
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Release Moto
      uses: ./.github/actions/moto-release/
      with:
        version: '${{ github.event.inputs.version }}'
        twine_user: '${{ secrets.TWINE_USERNAME }}'
        twine_pass: '${{ secrets.TWINE_PASSWORD }}'
        docker_user: '${{ secrets.DOCKER_USERNAME }}'
        docker_token: '${{ secrets.DOCKER_TOKEN }}'
